-- MySQL Script generated by MySQL Workbench
-- Thu May 24 17:56:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `ingredientes` MEDIUMTEXT NOT NULL,
  `cantidad` INT NULL,
  `campo1` VARCHAR(45) NULL,
  PRIMARY KEY (`ingredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProducto` INT NOT NULL,
  `Nombre` MEDIUMTEXT NULL,
  `precio` DECIMAL NULL,
  `ingrediente` MEDIUMTEXT NULL,
  `campo1` VARCHAR(45) NULL,
  `Inventario_ingredientes` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idProducto`, `Inventario_ingredientes`),
  INDEX `fk_Productos_Inventario1_idx` (`Inventario_ingredientes` ASC),
  CONSTRAINT `fk_Productos_Inventario1`
    FOREIGN KEY (`Inventario_ingredientes`)
    REFERENCES `mydb`.`Inventario` (`ingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `tarjeta` INT NULL,
  `clave` LONGTEXT NULL,
  `nombre` MEDIUMTEXT NULL,
  `apellido` MEDIUMTEXT NULL,
  `compra` MEDIUMTEXT NULL,
  `total` DECIMAL NULL,
  `fecha` DATE NULL,
  `Productos_idProducto` INT NOT NULL,
  PRIMARY KEY (`idFactura`, `Productos_idProducto`),
  INDEX `fk_Factura_Productos_idx` (`Productos_idProducto` ASC),
  CONSTRAINT `fk_Factura_Productos`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `mydb`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Id` INT NOT NULL,
  `Usuario` MEDIUMTEXT NULL,
  `Pass` MEDIUMTEXT NULL,
  `Tipo` MEDIUMTEXT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
